# Generated by Django 5.0.4 on 2024-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aral_app', '0002_alter_awardsmodel_certificate_alter_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='type',
            field=models.CharField(default='Technology', max_length=30),
        ),
    ]
