# Generated by Django 5.0.4 on 2024-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aral_app', '0005_portfoliomodel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='url',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
